# ========== COMPLETE BRANCH TO RBM/BDM MAPPING ==========
BRANCH_RBM_BDM_MAPPING = {
    # ALFAS RBM
    "BATHERY": {"RBM": "ALFAS", "BDM": "JOBIN"},
    "BATHERY FUTURE": {"RBM": "ALFAS", "BDM": "JOBIN"},
    "MANANTHAVADY": {"RBM": "ALFAS", "BDM": "JOBIN"},
    "MANANTHAVADY FUTURE": {"RBM": "ALFAS", "BDM": "JOBIN"},
    "myG CARE BATHERY": {"RBM": "ALFAS", "BDM": "JOBIN"},
    "KALPETTA": {"RBM": "ALFAS", "BDM": "JOBIN"},
    
    "BALUSSERY": {"RBM": "ALFAS", "BDM": "NIDEESH"},
    "BALUSSERY FUTURE": {"RBM": "ALFAS", "BDM": "NIDEESH"},
    "KUNNAMANGALAM FUTURE": {"RBM": "ALFAS", "BDM": "NIDEESH"},
    "MUKKOM": {"RBM": "ALFAS", "BDM": "NIDEESH"},
    "myG CARE PERUMANNA": {"RBM": "ALFAS", "BDM": "NIDEESH"},
    "NARIKKUNI": {"RBM": "ALFAS", "BDM": "NIDEESH"},
    "RAMANATTUKARA": {"RBM": "ALFAS", "BDM": "NIDEESH"},
    "THAMARASSERY FUTURE": {"RBM": "ALFAS", "BDM": "NIDEESH"},
    "THONDAYAD FUTURE": {"RBM": "ALFAS", "BDM": "NIDEESH"},
    "OLD THAMARASSERY": {"RBM": "ALFAS", "BDM": "NIDEESH"},
    "THONDAYAD": {"RBM": "ALFAS", "BDM": "NIDEESH"},
    "THAMARASSERY": {"RBM": "ALFAS", "BDM": "NIDEESH"},
    
    "CAFE YMCA": {"RBM": "ALFAS", "BDM": "SARATH"},
    "CAMWORLD": {"RBM": "ALFAS", "BDM": "SARATH"},
    "FEROKE FUTURE": {"RBM": "ALFAS", "BDM": "SARATH"},
    "HI LITE MALL": {"RBM": "ALFAS", "BDM": "SARATH"},
    "KINGSWAY": {"RBM": "ALFAS", "BDM": "SARATH"},
    "LANDSHIP MALL": {"RBM": "ALFAS", "BDM": "SARATH"},
    "NADAKKAVU FUTURE": {"RBM": "ALFAS", "BDM": "SARATH"},
    "P TOWER": {"RBM": "ALFAS", "BDM": "SARATH"},
    "POTTAMMAL FUTURE": {"RBM": "ALFAS", "BDM": "SARATH"},
    "PUTHIYARA": {"RBM": "ALFAS", "BDM": "SARATH"},
    "SABA": {"RBM": "ALFAS", "BDM": "SARATH"},
    "SABA MAHARANI": {"RBM": "ALFAS", "BDM": "SARATH"},
    "GALA POTTAMMAL": {"RBM": "ALFAS", "BDM": "SARATH"},
    "SEEMA": {"RBM": "ALFAS", "BDM": "SARATH"},
    
    "KOYILANDY": {"RBM": "ALFAS", "BDM": "SHAFEEK"},
    "KOYILANDY 2": {"RBM": "ALFAS", "BDM": "SHAFEEK"},
    "KUTTIYADI": {"RBM": "ALFAS", "BDM": "SHAFEEK"},
    "KUTTIYADI FUTURE": {"RBM": "ALFAS", "BDM": "SHAFEEK"},
    "PERAMBRA": {"RBM": "ALFAS", "BDM": "SHAFEEK"},
    "PERAMBRA FUTURE": {"RBM": "ALFAS", "BDM": "SHAFEEK"},
    "VADAKARA": {"RBM": "ALFAS", "BDM": "SHAFEEK"},
    "VADAKARA FUTURE": {"RBM": "ALFAS", "BDM": "SHAFEEK"},
    
    # GENERAL RBM
    "CORPORATE SALES": {"RBM": "GENERAL", "BDM": "GENERAL"},
    "eCommerce": {"RBM": "GENERAL", "BDM": "GENERAL"},
    "HARC": {"RBM": "GENERAL", "BDM": "GENERAL"},
    "HLRC": {"RBM": "GENERAL", "BDM": "GENERAL"},
    "MARKETING": {"RBM": "GENERAL", "BDM": "GENERAL"},
    "myG CARE THONDAYAD": {"RBM": "GENERAL", "BDM": "GENERAL"},
    "CUSTOMER CARE": {"RBM": "GENERAL", "BDM": "GENERAL"},
    "DEMO": {"RBM": "GENERAL", "BDM": "GENERAL"},
    "G-SPARE": {"RBM": "GENERAL", "BDM": "GENERAL"},
    "HEAD OFFICE": {"RBM": "GENERAL", "BDM": "GENERAL"},
    "myG Care HO": {"RBM": "GENERAL", "BDM": "GENERAL"},
    "myG INSTITUTE": {"RBM": "GENERAL", "BDM": "GENERAL"},
    "myG RDS": {"RBM": "GENERAL", "BDM": "GENERAL"},
    "MYGCARE ON WHEELS": {"RBM": "GENERAL", "BDM": "GENERAL"},
    "OFFSTAT": {"RBM": "GENERAL", "BDM": "GENERAL"},
    "UG-SMART CHOICE": {"RBM": "GENERAL", "BDM": "GENERAL"},
    "Z-DEAD STOCK": {"RBM": "GENERAL", "BDM": "GENERAL"},
    
    # MAHESH RBM
    "CHANGANASSERY": {"RBM": "MAHESH", "BDM": "ABHIJITH"},
    "ERATTUPETTA FUTURE": {"RBM": "MAHESH", "BDM": "ABHIJITH"},
    "KANJIRAPPALLY": {"RBM": "MAHESH", "BDM": "ABHIJITH"},
    "KANJIRAPPALLY FUTURE": {"RBM": "MAHESH", "BDM": "ABHIJITH"},
    "KOTTAYAM FUTURE": {"RBM": "MAHESH", "BDM": "ABHIJITH"},
    "NAGAMPADAM": {"RBM": "MAHESH", "BDM": "ABHIJITH"},
    "THIRUNAKKARA": {"RBM": "MAHESH", "BDM": "ABHIJITH"},
    
    "ALAPPUZHA": {"RBM": "MAHESH", "BDM": "RENJITHMON"},
    "ALAPPUZHA FUTURE": {"RBM": "MAHESH", "BDM": "RENJITHMON"},
    "CHERTHALA": {"RBM": "MAHESH", "BDM": "RENJITHMON"},
    "KAYAMKULAM": {"RBM": "MAHESH", "BDM": "RENJITHMON"},
    
    "ADOOR": {"RBM": "MAHESH", "BDM": "SIJU"},
    "ADOOR FUTURE": {"RBM": "MAHESH", "BDM": "SIJU"},
    "PATHANAMTHITTA FUTURE": {"RBM": "MAHESH", "BDM": "SIJU"},
    "RANNI FUTURE": {"RBM": "MAHESH", "BDM": "SIJU"},
    "THIRUVALLA": {"RBM": "MAHESH", "BDM": "SIJU"},
    "THIRUVALLA FUTURE": {"RBM": "MAHESH", "BDM": "SIJU"},
    
    # RENJITH RBM
    "CHALAKKUDI": {"RBM": "RENJITH", "BDM": "JALEEL"},
    "CHALAKKUDY FUTURE": {"RBM": "RENJITH", "BDM": "JALEEL"},
    "CHAVAKKAD": {"RBM": "RENJITH", "BDM": "JALEEL"},
    "CHAVAKKAD FUTURE": {"RBM": "RENJITH", "BDM": "JALEEL"},
    "IRINJALAKUDA FUTURE": {"RBM": "RENJITH", "BDM": "JALEEL"},
    "TRIPRAYAR": {"RBM": "RENJITH", "BDM": "JALEEL"},
    
    "MENAKA": {"RBM": "RENJITH", "BDM": "MARSHAL"},
    "PARAVOOR": {"RBM": "RENJITH", "BDM": "MARSHAL"},
    "PIRAVOM FUTURE": {"RBM": "RENJITH", "BDM": "MARSHAL"},
    "THRIPUNITHURA": {"RBM": "RENJITH", "BDM": "MARSHAL"},
    "VYPIN FUTURE": {"RBM": "RENJITH", "BDM": "MARSHAL"},
    "PIRAVOM": {"RBM": "RENJITH", "BDM": "MARSHAL"},
    
    "EDAPPALLY FUTURE": {"RBM": "RENJITH", "BDM": "MOBISH"},
    "FORUM MALL": {"RBM": "RENJITH", "BDM": "MOBISH"},
    "KADAVANTHRA": {"RBM": "RENJITH", "BDM": "MOBISH"},
    "PALARIVATTOM": {"RBM": "RENJITH", "BDM": "MOBISH"},
    "THOPPUMPADY FUTURE": {"RBM": "RENJITH", "BDM": "MOBISH"},
    
    "EAST FORT": {"RBM": "RENJITH", "BDM": "PRASEED"},
    "KUNNAMKULAM": {"RBM": "RENJITH", "BDM": "PRASEED"},
    "KURUPPAM ROAD": {"RBM": "RENJITH", "BDM": "PRASEED"},
    "OTTUPARA FUTURE": {"RBM": "RENJITH", "BDM": "PRASEED"},
    "POOTHOLE FUTURE": {"RBM": "RENJITH", "BDM": "PRASEED"},
    "THRISSUR EXHIBITION": {"RBM": "RENJITH", "BDM": "PRASEED"},
    
    "ALUVA": {"RBM": "RENJITH", "BDM": "SALAJ"},
    "ANGAMALY": {"RBM": "RENJITH", "BDM": "SALAJ"},
    "ANGAMALY FUTURE": {"RBM": "RENJITH", "BDM": "SALAJ"},
    "KOTHAMANGALAM FUTURE": {"RBM": "RENJITH", "BDM": "SALAJ"},
    "MUVATTUPUZHA": {"RBM": "RENJITH", "BDM": "SALAJ"},
    "MUVATTUPUZHA FUTURE": {"RBM": "RENJITH", "BDM": "SALAJ"},
    "PERUMBAVOOR FUTURE": {"RBM": "RENJITH", "BDM": "SALAJ"},
    "KOTHAMANGALAM": {"RBM": "RENJITH", "BDM": "SALAJ"},
    "PERUMBAVOOR": {"RBM": "RENJITH", "BDM": "SALAJ"},
    
    "ADIMALI": {"RBM": "RENJITH", "BDM": "SHAMEER"},
    "KATTAPPANA FUTURE": {"RBM": "RENJITH", "BDM": "SHAMEER"},
    "THODUPUZHA": {"RBM": "RENJITH", "BDM": "SHAMEER"},
    "THODUPUZHA FUTURE": {"RBM": "RENJITH", "BDM": "SHAMEER"},
    
    # SAMEEM RBM
    "IRITTY": {"RBM": "SAMEEM", "BDM": "ABHILASH"},
    "KANNUR FUTURE": {"RBM": "SAMEEM", "BDM": "ABHILASH"},
    "MAHE": {"RBM": "SAMEEM", "BDM": "ABHILASH"},
    "THALASSERY": {"RBM": "SAMEEM", "BDM": "ABHILASH"},
    "THALASSERY FUTURE": {"RBM": "SAMEEM", "BDM": "ABHILASH"},
    "THANA": {"RBM": "SAMEEM", "BDM": "ABHILASH"},
    "CAPITOL MALL": {"RBM": "SAMEEM", "BDM": "ABHILASH"},
    
    "KANHANGAD": {"RBM": "SAMEEM", "BDM": "ANOOP"},
    "KANHANGAD FUTURE": {"RBM": "SAMEEM", "BDM": "ANOOP"},
    "KASARGOD": {"RBM": "SAMEEM", "BDM": "ANOOP"},
    "KASARGOD FUTURE": {"RBM": "SAMEEM", "BDM": "ANOOP"},
    "UPPALA": {"RBM": "SAMEEM", "BDM": "ANOOP"},
    
    "BANK ROAD": {"RBM": "SAMEEM", "BDM": "FAISAL"},
    "PAYYANNUR": {"RBM": "SAMEEM", "BDM": "FAISAL"},
    "PAYYANNUR FUTURE": {"RBM": "SAMEEM", "BDM": "FAISAL"},
    "SNPARK": {"RBM": "SAMEEM", "BDM": "FAISAL"},
    "TALIPARAMBA": {"RBM": "SAMEEM", "BDM": "FAISAL"},
    
    # SAMEER RBM
    "BYPASS ROAD": {"RBM": "SAMEER", "BDM": "ASHIF"},
    "MANNARKAD FUTURE": {"RBM": "SAMEER", "BDM": "ASHIF"},
    "OTTAPALAM": {"RBM": "SAMEER", "BDM": "ASHIF"},
    "PALAKKAD FUTURE": {"RBM": "SAMEER", "BDM": "ASHIF"},
    "PATTAMBI FUTURE": {"RBM": "SAMEER", "BDM": "ASHIF"},
    "TB ROAD": {"RBM": "SAMEER", "BDM": "ASHIF"},
    "VADAKKENCHERRY FUTURE": {"RBM": "SAMEER", "BDM": "ASHIF"},
    "MANNARKKAD": {"RBM": "SAMEER", "BDM": "ASHIF"},
    "OLD PATTAMBI": {"RBM": "SAMEER", "BDM": "ASHIF"},
    "PATTAMBI": {"RBM": "SAMEER", "BDM": "ASHIF"},
    
    "EDAPPAL": {"RBM": "SAMEER", "BDM": "MANU"},
    "EDAPPAL FUTURE": {"RBM": "SAMEER", "BDM": "MANU"},
    "KOTTAKKAL": {"RBM": "SAMEER", "BDM": "MANU"},
    "KOTTAKKAL FUTURE": {"RBM": "SAMEER", "BDM": "MANU"},
    "MALAPPURAM": {"RBM": "SAMEER", "BDM": "MANU"},
    "PERINTHALMANNA FUTURE": {"RBM": "SAMEER", "BDM": "MANU"},
    "TIRUR": {"RBM": "SAMEER", "BDM": "MANU"},
    "VALANCHERY FUTURE": {"RBM": "SAMEER", "BDM": "MANU"},
    
    "AREEKODE FUTURE": {"RBM": "SAMEER", "BDM": "PRANAV"},
    "CHEMMAD": {"RBM": "SAMEER", "BDM": "PRANAV"},
    "EDAKKARA": {"RBM": "SAMEER", "BDM": "PRANAV"},
    "KONDOTTY": {"RBM": "SAMEER", "BDM": "PRANAV"},
    "KONDOTTY FUTURE": {"RBM": "SAMEER", "BDM": "PRANAV"},
    "MANJERY": {"RBM": "SAMEER", "BDM": "PRANAV"},
    "NILAMBUR FUTURE": {"RBM": "SAMEER", "BDM": "PRANAV"},
    "VENGARA": {"RBM": "SAMEER", "BDM": "PRANAV"},
    "WANDOOR": {"RBM": "SAMEER", "BDM": "PRANAV"},
    "NILAMBUR": {"RBM": "SAMEER", "BDM": "PRANAV"},
    "OLD NILAMBUR (CLOSED)": {"RBM": "SAMEER", "BDM": "PRANAV"},
    
    # VAISAKH RBM
    "KARUNAGAPPALLY": {"RBM": "VAISAKH", "BDM": "ABHIRAJ"},
    "KARUNAGAPPALLY FUTURE": {"RBM": "VAISAKH", "BDM": "ABHIRAJ"},
    "KOLLAM": {"RBM": "VAISAKH", "BDM": "ABHIRAJ"},
    "KOLLAM FUTURE": {"RBM": "VAISAKH", "BDM": "ABHIRAJ"},
    "KOTTARAKKARA": {"RBM": "VAISAKH", "BDM": "ABHIRAJ"},
    "PUNALUR FUTURE": {"RBM": "VAISAKH", "BDM": "ABHIRAJ"},
    
    "ATTINGAL": {"RBM": "VAISAKH", "BDM": "AMAL"},
    "ATTINGAL FUTURE": {"RBM": "VAISAKH", "BDM": "AMAL"},
    "KILIMANOOR": {"RBM": "VAISAKH", "BDM": "AMAL"},
    "VENJARAMOODU FUTURE": {"RBM": "VAISAKH", "BDM": "AMAL"},
    
    "AAKKULAM FUTURE": {"RBM": "VAISAKH", "BDM": "NIYAD"},
    "KARAMANA": {"RBM": "VAISAKH", "BDM": "NIYAD"},
    "PANAVILA FUTURE": {"RBM": "VAISAKH", "BDM": "NIYAD"},
    "PATTOM": {"RBM": "VAISAKH", "BDM": "NIYAD"},
    "PAZHAVANGADI": {"RBM": "VAISAKH", "BDM": "NIYAD"},
}

# ========== BRANCH TO DISTRICT MAPPING ==========
BRANCH_DISTRICT_MAPPING = {
    "AAKKULAM FUTURE": "Thiruvananthapuram",
    "ADIMALI": "Idukki",
    "ADOOR": "Pathanamthitta",
    "ADOOR FUTURE": "Pathanamthitta",
    "ALAPPUZHA": "Alappuzha",
    "ALAPPUZHA FUTURE": "Alappuzha",
    "ALUVA": "Ernakulam",
    "ANGAMALY": "Ernakulam",
    "ANGAMALY FUTURE": "Ernakulam",
    "AREEKODE FUTURE": "Malappuram",
    "ATTINGAL": "Thiruvananthapuram",
    "ATTINGAL FUTURE": "Thiruvananthapuram",
    "BALUSSERY": "Kozhikode",
    "BALUSSERY FUTURE": "Kozhikode",
    "BANK ROAD": "Kannur",
    "BATHERY": "Wayanad",
    "BATHERY FUTURE": "Wayanad",
    "BYPASS ROAD": "Palakkad",
    "CAFE YMCA": "Kozhikode",
    "CAMWORLD": "Kozhikode",
    "CAPITOL MALL": "Kannur",
    "CHALAKKUDI": "Thrissur",
    "CHALAKKUDY FUTURE": "Thrissur",
    "CHANGANASSERY": "Kottayam",
    "CHAVAKKAD": "Thrissur",
    "CHAVAKKAD FUTURE": "Thrissur",
    "CHEMMAD": "Malappuram",
    "CHERTHALA": "Alappuzha",
    "CORPORATE SALES": "Corporate",
    "CUSTOMER CARE": "Corporate",
    "DEMO": "Corporate",
    "EAST FORT": "Thrissur",
    "EDAKKARA": "Malappuram",
    "EDAPPAL": "Malappuram",
    "EDAPPAL FUTURE": "Malappuram",
    "EDAPPALLY FUTURE": "Ernakulam",
    "eCommerce": "Corporate",
    "ERATTUPETTA FUTURE": "Kottayam",
    "FEROKE FUTURE": "Kozhikode",
    "FORUM MALL": "Ernakulam",
    "G-SPARE": "Corporate",
    "GALA POTTAMMAL": "Kozhikode",
    "HARC": "Corporate",
    "HEAD OFFICE": "Corporate",
    "HI LITE MALL": "Kozhikode",
    "HLRC": "Corporate",
    "IRINJALAKUDA FUTURE": "Thrissur",
    "IRITTY": "Kannur",
    "KADAVANTHRA": "Ernakulam",
    "KALPETTA": "Wayanad",
    "KANHANGAD": "Kasaragod",
    "KANHANGAD FUTURE": "Kasaragod",
    "KANJIRAPPALLY": "Kottayam",
    "KANJIRAPPALLY FUTURE": "Kottayam",
    "KANNUR FUTURE": "Kannur",
    "KARAMANA": "Thiruvananthapuram",
    "KARUNAGAPPALLY": "Kollam",
    "KARUNAGAPPALLY FUTURE": "Kollam",
    "KASARGOD": "Kasaragod",
    "KASARGOD FUTURE": "Kasaragod",
    "KATTAPPANA FUTURE": "Idukki",
    "KAYAMKULAM": "Alappuzha",
    "KILIMANOOR": "Thiruvananthapuram",
    "KINGSWAY": "Kozhikode",
    "KOLLAM": "Kollam",
    "KOLLAM FUTURE": "Kollam",
    "KONDOTTY": "Malappuram",
    "KONDOTTY FUTURE": "Malappuram",
    "KOTHAMANGALAM": "Ernakulam",
    "KOTHAMANGALAM FUTURE": "Ernakulam",
    "KOTTAKKAL": "Malappuram",
    "KOTTAKKAL FUTURE": "Malappuram",
    "KOTTARAKKARA": "Kollam",
    "KOTTAYAM FUTURE": "Kottayam",
    "KOYILANDY": "Kozhikode",
    "KOYILANDY 2": "Kozhikode",
    "KUNNAMANGALAM FUTURE": "Kozhikode",
    "KUNNAMKULAM": "Thrissur",
    "KURUPPAM ROAD": "Thrissur",
    "KUTTIYADI": "Kozhikode",
    "KUTTIYADI FUTURE": "Kozhikode",
    "LANDSHIP MALL": "Kozhikode",
    "MAHE": "Kannur",
    "MALAPPURAM": "Malappuram",
    "MANANTHAVADY": "Wayanad",
    "MANANTHAVADY FUTURE": "Wayanad",
    "MANJERY": "Malappuram",
    "MANNARKAD FUTURE": "Palakkad",
    "MANNARKKAD": "Palakkad",
    "MARKETING": "Corporate",
    "MENAKA": "Ernakulam",
    "MUKKOM": "Kozhikode",
    "MUVATTUPUZHA": "Ernakulam",
    "MUVATTUPUZHA FUTURE": "Ernakulam",
    "myG CARE BATHERY": "Wayanad",
    "myG CARE PERUMANNA": "Kozhikode",
    "myG CARE THONDAYAD": "Kozhikode",
    "myG Care HO": "Corporate",
    "myG INSTITUTE": "Corporate",
    "myG RDS": "Corporate",
    "MYGCARE ON WHEELS": "Corporate",
    "NADAKKAVU FUTURE": "Kozhikode",
    "NAGAMPADAM": "Kottayam",
    "NARIKKUNI": "Kozhikode",
    "NILAMBUR": "Malappuram",
    "NILAMBUR FUTURE": "Malappuram",
    "OFFSTAT": "Corporate",
    "OLD NILAMBUR (CLOSED)": "Malappuram",
    "OLD PATTAMBI": "Palakkad",
    "OLD THAMARASSERY": "Kozhikode",
    "OTTAPALAM": "Thrissur",
    "OTTUPARA FUTURE": "Palakkad",
    "P TOWER": "Kozhikode",
    "PALAKKAD FUTURE": "Palakkad",
    "PALARIVATTOM": "Ernakulam",
    "PANAVILA FUTURE": "Thiruvananthapuram",
    "PARAVOOR": "Ernakulam",
    "PATHANAMTHITTA FUTURE": "Pathanamthitta",
    "PATTAMBI": "Palakkad",
    "PATTAMBI FUTURE": "Palakkad",
    "PATTOM": "Thiruvananthapuram",
    "PAYYANNUR": "Kannur",
    "PAYYANNUR FUTURE": "Kannur",
    "PAZHAVANGADI": "Thiruvananthapuram",
    "PERAMBRA": "Kozhikode",
    "PERAMBRA FUTURE": "Kozhikode",
    "PERINTHALMANNA FUTURE": "Malappuram",
    "PERUMBAVOOR": "Ernakulam",
    "PERUMBAVOOR FUTURE": "Ernakulam",
    "PIRAVOM": "Ernakulam",
    "PIRAVOM FUTURE": "Ernakulam",
    "POOTHOLE FUTURE": "Thrissur",
    "POTTAMMAL FUTURE": "Kozhikode",
    "PUNALUR FUTURE": "Kollam",
    "PUTHIYARA": "Kozhikode",
    "RAMANATTUKARA": "Kozhikode",
    "RANNI FUTURE": "Pathanamthitta",
    "SABA": "Kozhikode",
    "SABA MAHARANI": "Kozhikode",
    "SEEMA": "Kozhikode",
    "SNPARK": "Kannur",
    "TALIPARAMBA": "Kannur",
    "TB ROAD": "Palakkad",
    "THALASSERY": "Kannur",
    "THALASSERY FUTURE": "Kannur",
    "THAMARASSERY": "Kozhikode",
    "THAMARASSERY FUTURE": "Kozhikode",
    "THANA": "Kannur",
    "THIRUNAKKARA": "Kottayam",
    "THIRUVALLA": "Pathanamthitta",
    "THIRUVALLA FUTURE": "Pathanamthitta",
    "THODUPUZHA": "Idukki",
    "THODUPUZHA FUTURE": "Idukki",
    "THONDAYAD": "Kozhikode",
    "THONDAYAD FUTURE": "Kozhikode",
    "THOPPUMPADY FUTURE": "Ernakulam",
    "THRIPUNITHURA": "Ernakulam",
    "THRISSUR EXHIBITION": "Thrissur",
    "TIRUR": "Malappuram",
    "TRIPRAYAR": "Thrissur",
    "UG-SMART CHOICE": "Corporate",
    "UPPALA": "Kasaragod",
    "VADAKARA": "Kozhikode",
    "VADAKARA FUTURE": "Kozhikode",
    "VADAKKENCHERRY FUTURE": "Palakkad",
    "VALANCHERY FUTURE": "Malappuram",
    "VENGARA": "Malappuram",
    "VENJARAMOODU FUTURE": "Thiruvananthapuram",
    "VYPIN FUTURE": "Ernakulam",
    "WANDOOR": "Malappuram",
    "Z-DEAD STOCK": "Corporate"
}

# ========== DISTRICT TO STATE MAPPING ==========
DISTRICT_STATE_MAPPING = {
    "Thiruvananthapuram": "Kerala",
    "Idukki": "Kerala", 
    "Pathanamthitta": "Kerala",
    "Alappuzha": "Kerala",
    "Ernakulam": "Kerala",
    "Malappuram": "Kerala",
    "Kozhikode": "Kerala",
    "Kannur": "Kerala",
    "Kasaragod": "Kerala",
    "Kottayam": "Kerala",
    "Kollam": "Kerala",
    "Thrissur": "Kerala",
    "Wayanad": "Kerala",
    "Palakkad": "Kerala",
    "Corporate": "Corporate"
}

# Google Sheets Configuration
GOOGLE_SHEET_ID = "1x-jdXZaT_pBhXSE0gQhF5i2eYbbwH-F9f2PNVaX6Io4"
GOOGLE_SHEET_URL = f"https://docs.google.com/spreadsheets/d/{GOOGLE_SHEET_ID}/export?format=csv"
